baseURL = 'https://h3rmt.zip/'
languageCode = 'en-us'
title = 'H3rmt Homepage'
theme = 'PaperMod'

params.showReadingTime = true
params.showWordCount = true
params.showShareButtons = true

[params.homeInfoParams]
title = "H3rmt Homepage"
Content = "Welcome to H3rmt's Homepage."

[[menu.main]]
identifier = 'sites'
name = 'Websites'
url = '/sites/'
weight = 10

[[menu.main]]
identifier = 'archive'
name = 'Archive'
url = '/archive/'
weight = 20

[[menu.main]]
identifier = 'Github'
name = 'GitHub'
url = 'https://github.com/H3rmt'
weight = 30